/*
 * song_play.java

 *
 * Created on __DATE__, __TIME__
 */

package admin;

import java.awt.GridLayout;
import java.util.List;

import javax.swing.JLabel;

import model.song;

/**
 *
 * @author  __USER__
 */
public class song_play extends javax.swing.JFrame {

	/** Creates new form song_play */
	public song_play() {
		initComponents();
		chakangeku();

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u64ad\u653e\u4eca\u5929\u7684\u8282\u76ee\u5355");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 512,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 222,
				Short.MAX_VALUE));

		jLabel2.setText("\u6b63\u5728\u64ad\u653e\u6b4c\u66f2\uff1a");

		jButton1.setText("\u6682\u505c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u4e0b\u4e00\u9996");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addGap(205, 205, 205)
										.addComponent(jLabel1)
										.addContainerGap(211, Short.MAX_VALUE))
						.addComponent(jPanel2,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(27, 27, 27)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												96,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												100, Short.MAX_VALUE)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2)
										.addGap(65, 65, 65)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(31, 31, 31)
										.addComponent(jLabel1)
										.addGap(18, 18, 18)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												17, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								17,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(23,
																				23,
																				23))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton1)
																						.addComponent(
																								jButton2))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGap(14, 14, 14)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (this.jButton1.getText().equals("暂停")){
			this.jButton1.setText("播放");
		}else if (this.jButton1.getText().equals("播放"))
			this.jButton1.setText("暂停");
	}

	int i = 0;


	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (i >= list.size())
			i = 0;
		this.jLabel3.removeAll();
		this.jLabel3.setVisible(false);
		this.jLabel3.setText(JL[i].getText());
		this.jLabel3.setVisible(true);
		i++;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new song_play().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables
	admin ad = new admin();
	List<song> list = ad.chakangeku_today();
	JLabel[] JL = new JLabel[list.size()];

	//查看歌库
	public void chakangeku() {

		JLabel[] JL1 = new JLabel[list.size()];
		JLabel[] JL2 = new JLabel[list.size()];
		JLabel[] JL3 = new JLabel[list.size()];
		JLabel[] JL4 = new JLabel[list.size()];
		JL[0] = new JLabel("歌名");
		JL1[0] = new JLabel("歌手");
		JL2[0] = new JLabel("主题");
		JL3[0] = new JLabel("日期");
		JL4[0] = new JLabel("是否按顺序播放");

		jPanel2.add(JL[0]);
		jPanel2.add(JL1[0]);
		jPanel2.add(JL2[0]);
		jPanel2.add(JL3[0]);
		jPanel2.add(JL4[0]);
		jPanel2.setLayout(new GridLayout(list.size() + 1, 5, 1, 1));
		for (int i = 0; i < list.size(); i++) {
			JL[i] = new JLabel(list.get(i).getSongName());
			JL1[i] = new JLabel(list.get(i).getAuthor());
			JL2[i] = new JLabel(list.get(i).getTheme());
			JL3[i] = new JLabel(list.get(i).getDate());
			jPanel2.add(JL[i]);
			jPanel2.add(JL1[i]);
			jPanel2.add(JL2[i]);
			jPanel2.add(JL3[i]);
			if (list.get(i).isIFSEQUENCE()) {
				JL4[i] = new JLabel("是");
				jPanel2.add(JL4[i]);
			} else {
				JL4[i] = new JLabel("否");
				jPanel2.add(JL4[i]);
			}

		}
		this.jLabel3.setText(JL[1].getText());
	}

}