/*
 * Choice_course_Menus.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Container;
import java.awt.event.ItemEvent;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import untity.Admin_Impl;
import untity.Student_Impl;
import entity.Full_course;
import entity.Student;

/**
 *
 * @author  __USER__
 */
public class Choice_course_Menus extends javax.swing.JFrame {
	Student stu;
	/** Creates new form Choice_course_Menus */
	ArrayList<Full_course> st_course;//全局变量
	ArrayList<String> tea_ids = new ArrayList<String>();
    ArrayList<String>co_ids=new ArrayList<String>();
    DefaultTableModel defaultTableModel;
	private void init() throws Exception {
		tea_ids.removeAll(tea_ids);
		co_ids.removeAll(co_ids);
		st_course = Student_Impl.select_couse();
		Object title[] = { "序号", "课程", "学分", "教师", "上课地点", "课程数量"};
		Object detail[][] = new Object[st_course.size()][6];
		for (int i = 0; i < st_course.size(); i++) {
			    co_ids.add(Integer.toString(st_course.get(i).getCo_id()));
				detail[i][0] = Integer.toString(i+1);
				detail[i][1] = st_course.get(i).getCourse();
				detail[i][2] = Integer.toString(st_course.get(i).getCredit());
				detail[i][3] = st_course.get(i).getName();
				detail[i][4] = st_course.get(i).getCo_time();
				detail[i][5] = st_course.get(i).getNumber();
				tea_ids.add(Integer.toString(st_course.get(i).getTea_id()));
		}
		defaultTableModel=new DefaultTableModel(detail, title);
		this.jTable1.setModel(defaultTableModel);
	}

	public Choice_course_Menus(Student st) {
		stu = st;
		initComponents();
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		ImageIcon bk = new ImageIcon(this.getClass().getResource("../背景.jpg"));
		jLabel1.setIcon(bk);
		jLabel1.setBounds(0, 0, 800, 500);
		this.getLayeredPane().add(jLabel1, new Integer(Integer.MIN_VALUE));
		Container panel = this.getContentPane();
		((JPanel) panel).setOpaque(false);
		try {
			init();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("jLabel1");

		jLabel2.setFont(new java.awt.Font("宋体", 0, 24));
		jLabel2.setText("\u9009\u8bfe\u6a21\u5757");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel3.setForeground(new java.awt.Color(255, 0, 0));
		jLabel3
				.setText("\u5355\u51fb\u8868\u683c\u7684\u67d0\u4e00\u884c\u5373\u53ef\u9009\u8bfe");

		jButton1.setText("\u6211\u7684\u8bfe\u8868");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u5237\u65b0");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u8fd4\u56de");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												629, Short.MAX_VALUE)
										.addComponent(jButton2))
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 744,
								Short.MAX_VALUE)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(130, 130, 130)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												285, Short.MAX_VALUE)
										.addComponent(
												jButton3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												93,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(143, 143, 143)).addGroup(
								layout.createSequentialGroup().addGap(318, 318,
										318).addComponent(jLabel2)
										.addContainerGap(330, Short.MAX_VALUE))
						.addGroup(
								layout.createSequentialGroup().addGap(239, 239,
										239).addComponent(jLabel3)
										.addContainerGap(325, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jButton2))
																		.addGap(
																				29,
																				29,
																				29))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												192,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3)
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton3)
														.addComponent(jButton1))
										.addContainerGap(49, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		if (evt.getClickCount() == 1) {
			int id = Integer.valueOf(((String) this.jTable1.getValueAt(
					this.jTable1.getSelectedRow(), 0)));
			  System.out.println("课程id "+co_ids.get(id-1)+"教师id "+tea_ids.get(id-1));
			if (Student_Impl.iscourse(Integer.parseInt(co_ids.get(id-1)), stu.getName()) == true) {
				JOptionPane.showMessageDialog(this, "你已经选择了这门课");
			} else {
				try {
					Student_Impl.choice(stu.getId(), Integer.parseInt(co_ids.get(id-1)), Integer.parseInt(tea_ids.get(id - 1)));
					Student_Impl.course_1(Integer.parseInt(co_ids.get(id-1)));
					init();
					JOptionPane.showMessageDialog(this, "添加成功");
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			init();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		new Stu_course_Menus(stu).setVisible(true);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		new Student_Menus(stu).setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}