/*
 * Login_Menus.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Container;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import untity.Admin_Impl;
import untity.Student_Impl;
import untity.Teacher_Impl;
import entity.Admin;
import entity.Student;
import entity.Teacher;

/**
 *
 * @author  __USER__
 */
public class Login_Menus extends javax.swing.JFrame {
	Admin ad;
	Student st;
	Teacher tea;

	/** Creates new form Login_Menus */
	public Login_Menus() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		this.jPasswordField1.setEchoChar('*');
		ImageIcon bk = new ImageIcon(this.getClass().getResource("../背景.jpg"));
		jLabel1.setIcon(bk);
		jLabel1.setBounds(0, 0, 500, 300);
		this.getLayeredPane().add(jLabel1, new Integer(Integer.MIN_VALUE));
		Container panel = this.getContentPane();
		((JPanel) panel).setOpaque(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		buttonGroup3 = new javax.swing.ButtonGroup();
		buttonGroup4 = new javax.swing.ButtonGroup();
		buttonGroup5 = new javax.swing.ButtonGroup();
		buttonGroup6 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("jLabel1");

		jLabel2.setText("\u59d3\u540d\uff1a");

		jLabel3.setText("\u5bc6\u7801\uff1a");

		buttonGroup1.add(jRadioButton1);
		jRadioButton1.setText("\u7ba1\u7406\u5458");

		buttonGroup1.add(jRadioButton2);
		jRadioButton2.setText("\u5b66\u751f");

		buttonGroup1.add(jRadioButton3);
		jRadioButton3.setText("\u6559\u5e08");

		jButton1.setText("\u767b\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u91cd\u7f6e");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jCheckBox1.setText("\u663e\u793a\u5bc6\u7801");
		jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jCheckBox1MouseClicked(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("宋体", 0, 24));
		jLabel4.setText("\u767b\u5f55\u754c\u9762");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addComponent(
										jLabel1).addContainerGap(404,
										Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										173, Short.MAX_VALUE).addComponent(
										jLabel4).addGap(187, 187, 187))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(69, 69, 69)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addGap(30, 30, 30)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jPasswordField1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																218,
																Short.MAX_VALUE)
														.addComponent(
																jCheckBox1,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addContainerGap(94, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(107, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addGap(
																				124,
																				124,
																				124)
																		.addComponent(
																				jButton2))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jRadioButton1)
																		.addGap(
																				26,
																				26,
																				26)
																		.addComponent(
																				jRadioButton2)
																		.addGap(
																				33,
																				33,
																				33)
																		.addComponent(
																				jRadioButton3)))
										.addGap(99, 99, 99)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addGap(20, 20, 20)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																22,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCheckBox1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jRadioButton2)
														.addComponent(
																jRadioButton3)
														.addComponent(
																jRadioButton1))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addGap(33, 33, 33)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {
		if (this.jCheckBox1.isSelected()) {
			this.jPasswordField1.setEchoChar((char) 0);
		} else {
			this.jPasswordField1.setEchoChar('*');
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextField1.setText("");
		this.jPasswordField1.setText("");

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		String name = this.jTextField1.getText();
		String pa = this.jPasswordField1.getText();
		//管理员
		if (this.jRadioButton1.isSelected()) {
			try {
				ad = Admin_Impl.login(name, pa);
				if (ad == null) {
					JOptionPane.showMessageDialog(this, "密码或者姓名错误");
				} else {
					JOptionPane.showMessageDialog(this, "登录成功");
					this.dispose();
					new Admin_Menus(ad).setVisible(true);
				}

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		} else if (this.jRadioButton2.isSelected()) {//学生
			try {
				st = Student_Impl.login(name, pa);
				if (st == null) {
					JOptionPane.showMessageDialog(this, "密码或者姓名错误");
				} else {
					JOptionPane.showMessageDialog(this, "登录成功");
					this.dispose();
					new Student_Menus(st).setVisible(true);
				}

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		} else if (this.jRadioButton3.isSelected()) {//教师
			try {
				tea = Teacher_Impl.login(name, pa);
				if (tea == null) {
					JOptionPane.showMessageDialog(this, "密码或者姓名错误");
				} else {
					JOptionPane.showMessageDialog(this, "登录成功");
					this.dispose();
					
					new Teacher_Menus(tea).setVisible(true);
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		} else {
			JOptionPane.showMessageDialog(this, "请选择身份");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login_Menus().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.ButtonGroup buttonGroup3;
	private javax.swing.ButtonGroup buttonGroup4;
	private javax.swing.ButtonGroup buttonGroup5;
	private javax.swing.ButtonGroup buttonGroup6;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}