/*
 * T_grade_Menus.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Container;
import java.awt.event.ItemEvent;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import untity.Teacher_Impl;

import entity.Full_class_grade;
import entity.Teacher;

/**
 *
 * @author  __USER__
 */
public class T_grade_Menus extends javax.swing.JFrame {
	Teacher teacher;
	String current_course;
	ArrayList<Full_class_grade> full_class_grade = new ArrayList<Full_class_grade>();
	ArrayList<String> courselist = new ArrayList<String>();
	ArrayList<String> stu_idlist = new ArrayList<String>();
	int current_row;//当前鼠标点击的位置
	DefaultTableModel cellEditor;

	//下拉框初始化
	private void init2() {
		courselist = Teacher_Impl.get_courselist(teacher.getId());
		this.jComboBox1.addItem("请选择课程");
		for (String course : courselist) {
			this.jComboBox1.addItem(course);

		}
	}

	private void init1() {
		Object title[] = { "序号", "课程", "学生", "学号", "分数", "专业" };
		Object detail[][] = new Object[full_class_grade.size()][6];
		this.jTable1.setModel(new DefaultTableModel(detail, title));
	}

	private void init(String course) {
		try {
			full_class_grade = Teacher_Impl.get_class_grade(course);
			Object title[] = { "序号", "课程", "学生", "学号", "分数", "专业" };
			Object detail[][] = new Object[full_class_grade.size()][6];
			for (int i = 0; i < full_class_grade.size(); i++) {
				detail[i][0] = Integer.toString(i + 1);
				detail[i][1] = full_class_grade.get(i).getCourse();
				detail[i][2] = full_class_grade.get(i).getName();
				detail[i][3] = full_class_grade.get(i).getXuehao();
				detail[i][4] = Float.toString(full_class_grade.get(i)
						.getGrade());
				detail[i][5] = full_class_grade.get(i).getMajor();
				stu_idlist.add(Integer.toString(full_class_grade.get(i)
						.getSt_id()));
			}
			cellEditor = new DefaultTableModel(detail, title) {
				public boolean isCellEditable(int row, int column) {
					if (column == 4) {
						return true;
					} else {
						return false;
					}
				}
			};
			this.jTable1.setModel(cellEditor);
			this.jTable1.isCellEditable(0, 4);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/** Creates new form T_grade_Menus */
	public T_grade_Menus(Teacher tea) {
		teacher = tea;
		initComponents();
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		init1();
		init2();
		ImageIcon bk = new ImageIcon(this.getClass().getResource("../背景.jpg"));
		jLabel2.setIcon(bk);
		jLabel2.setBounds(0, 0, 910, 550);
		this.getLayeredPane().add(jLabel2, new Integer(Integer.MIN_VALUE));
		Container panel = this.getContentPane();
		((JPanel) panel).setOpaque(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
jTable1 = new javax.swing.JTable();
jLabel3 = new javax.swing.JLabel();
jButton1 = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();
jButton5 = new javax.swing.JButton();
jComboBox1 = new javax.swing.JComboBox();
jButton4 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

jLabel1.setFont(new java.awt.Font("宋体", 0, 24));
jLabel1.setText("\u6210\u7ee9\u6a21\u5757");

jLabel2.setText("jLabel2");

jTable1.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		{null, null, null, null},
		{null, null, null, null},
		{null, null, null, null},
		{null, null, null, null}
	},
	new String [] {
		"Title 1", "Title 2", "Title 3", "Title 4"
	}
));
jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTable1MouseClicked(evt);
}
});
jScrollPane1.setViewportView(jTable1);

jLabel3.setFont(new java.awt.Font("宋体", 0, 15));
jLabel3.setText("\u8bfe\u7a0b\u540d\u5b57\uff1a");

jButton1.setText("\u786e\u5b9a");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

jButton2.setText("\u5237\u65b0");
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});

jButton3.setText("\u6309\u6210\u7ee9\u6392\u540d");
jButton3.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton3ActionPerformed(evt);
}
});

jButton5.setText("\u8fd4\u56de");
jButton5.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton5ActionPerformed(evt);
}
});


jComboBox1.addItemListener(new java.awt.event.ItemListener() {
public void itemStateChanged(java.awt.event.ItemEvent evt) {
jComboBox1ItemStateChanged(evt);
}
});

jButton4.setText("\u786e\u5b9a\u4fee\u6539\u6210\u7ee9");
jButton4.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton4ActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(155, 155, 155)
.addComponent(jButton3)
.addGap(172, 172, 172)
.addComponent(jButton4)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
.addComponent(jButton5)
.addGap(82, 82, 82))
.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel2)
.addGap(339, 339, 339)
.addComponent(jLabel1)
.addGap(372, 372, 372))
.addGroup(layout.createSequentialGroup()
.addComponent(jButton2)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
.addComponent(jLabel3)
.addGap(18, 18, 18)
.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(71, 71, 71)
.addComponent(jButton1)
.addGap(63, 63, 63))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel2)
.addGap(58, 58, 58)
.addComponent(jButton2)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(jButton1)
.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(33, 33, 33)))
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jButton3)
.addComponent(jButton4)
.addComponent(jButton5))
.addContainerGap(54, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		ArrayList<Full_class_grade> full_class_grade = new ArrayList<Full_class_grade>();
		try {
			full_class_grade=Teacher_Impl.get_pai(current_course);
			Object title[] = { "序号", "课程", "学生", "学号", "分数", "专业" };
			Object detail[][] = new Object[full_class_grade.size()][6];
			for (int i = 0; i < full_class_grade.size(); i++) {
				detail[i][0] = Integer.toString(i + 1);
				detail[i][1] = full_class_grade.get(i).getCourse();
				detail[i][2] = full_class_grade.get(i).getName();
				detail[i][3] = full_class_grade.get(i).getXuehao();
				detail[i][4] = Float.toString(full_class_grade.get(i)
						.getGrade());
				detail[i][5] = full_class_grade.get(i).getMajor();
				stu_idlist.add(Integer.toString(full_class_grade.get(i)
						.getSt_id()));
			}
			cellEditor = new DefaultTableModel(detail, title) {
				public boolean isCellEditable(int row, int column) {
					if (column == 4) {
						return true;
					} else {
						return false;
					}
				}
			};
			this.jTable1.setModel(cellEditor);
			this.jTable1.isCellEditable(0, 4);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

		this.jTable1.getCellEditor().stopCellEditing();//取消鼠标光标
		//获取分数
		String grade = (String) this.jTable1.getValueAt(current_row, 4);
		//System.out.println(stu_idlist.get(current_row));
		//System.out.println(full_class_grade.get(current_row).getCo_id());
		//更新成绩

		try {
			Teacher_Impl.update_grade(Integer.parseInt(stu_idlist
					.get(current_row)), Float.parseFloat(grade),
					full_class_grade.get(current_row).getCo_id());
			JOptionPane.showMessageDialog(this, "成绩修改成功");
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		if (evt.getClickCount() == 1) {
			current_row = this.jTable1.getSelectedRow();
		}
	}

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == ItemEvent.SELECTED) {
			current_course = (String) this.jComboBox1.getSelectedItem();
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		init(current_course);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (current_course.equals("请选择课程")) {
			JOptionPane.showMessageDialog(this, "请选择课程");
		} else {
			init(current_course);
		}
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		new Teacher_Menus(teacher).setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}