/*
 * ImageMenu.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.util.ArrayList;

import javax.swing.ImageIcon;

/**
 *
 * @author  __USER__
 */
public class ImageMenu extends javax.swing.JFrame {

	/** Creates new form ImageMenu */
	public ImageMenu() {
		initComponents();
		imgrote();
	}

	int i=0;
	ArrayList<Image> imgs = new ArrayList<Image>();
    private void imgrote() {
		for (i=1; i<=5; i++) {
			Image img = new ImageIcon("img\\"+i+".jpg").getImage().getScaledInstance(
					this.jButton1.getWidth(), this.jButton1.getHeight(),
					Image.SCALE_SMOOTH);
			imgs.add(img);
		}
    this.jButton1.setIcon(new ImageIcon(imgs.get(0)));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setBorder(null);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 440,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(27, 27, 27).addComponent(
						jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(126, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if(i==4)
			i=0;
		this.jButton1.setIcon(new ImageIcon(imgs.get(i)));
		i++;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ImageMenu().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	// End of variables declaration//GEN-END:variables

}