/*
 * Coursetable.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.Course;
import model.Student;
import model.Student.myexception;

/**
 *
 * @author  __USER__
 */
public class Coursetable extends javax.swing.JFrame {

	/** Creates new form Coursetable */
	public void load(String student, String number) {
		try {
			this.jLabel3.setText(student);
			this.jLabel4.setText(number);
			ArrayList<Course> course = Student.rob_course();
			Object title[] = { "序号", "上课时间", "课程","学分","课程老师" };
			Object detail[][] = new Object[course.size()][5];
			for (int i = 0; i < course.size(); i++) {
				detail[i][0] = course.get(i).getId();
				detail[i][1] = course.get(i).getCoursetime();
				detail[i][2] = course.get(i).getCourse();
				detail[i][3]=course.get(i).getCredit();
				detail[i][4] = course.get(i).getTeacher();

			}
			this.jTable1.setModel(new DefaultTableModel(detail, title));
			jTable1.setEnabled(false);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(this, "错误");
			e.printStackTrace();
		}
	}

	public Coursetable(String student, String number) {
		initComponents();
		this.setLocationRelativeTo(null);
		load(student, number);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("\u8bfe    \u8868");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u5237\u65b0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setText("\u8bf7\u8f93\u5165ID\uff1a");

		jButton2.setText("\u62a2\u8bfe");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setForeground(new java.awt.Color(255, 0, 0));
		jLabel3.setText("jLabel3");

		jLabel4.setForeground(new java.awt.Color(255, 0, 0));
		jLabel4.setText("jLabel4");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(148, 148, 148)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												119, Short.MAX_VALUE)
										.addComponent(jButton1))
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 406,
								Short.MAX_VALUE)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												182,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												50, Short.MAX_VALUE)
										.addComponent(jButton2)
										.addContainerGap()).addGroup(
								layout.createSequentialGroup().addGap(108, 108,
										108).addComponent(jLabel3).addGap(49,
										49, 49).addComponent(jLabel4)
										.addContainerGap(145, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(jButton1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												206,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(jLabel3))
										.addGap(22, 22, 22)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton2)))
										.addContainerGap(73, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)  {
		// TODO add your handling code here:
		int id=Integer.parseInt(this.jTextField1.getText());
		String student=this.jLabel3.getText();
		String number=this.jLabel4.getText();
		
			
			
			try {
				Student.rabcourse(id,student,number);
				JOptionPane.showMessageDialog(this,"抢课成功");
			} catch (myexception e) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(this, "该课程你已经抢过");
			} catch (Exception e) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(this, "错误");
				e.printStackTrace();
			}
			
		
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {

			ArrayList<Course> course = Student.rob_course();
			Object title[] = { "序号", "上课时间", "课程", "课程老师" };
			Object detail[][] = new Object[course.size()][4];
			for (int i = 0; i < course.size(); i++) {
				detail[i][0] = course.get(i).getId();
				detail[i][1] = course.get(i).getCoursetime();
				detail[i][2] = course.get(i).getCourse();
				detail[i][3] = course.get(i).getTeacher();

			}
			this.jTable1.setModel(new DefaultTableModel(detail, title));
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(this, "错误");
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Coursetable(null, null).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}