/*
 * Insertgrade.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.B;
import model.Teacher;

/**
 *
 * @author  __USER__
 */
public class Insertgrade extends javax.swing.JFrame {
	Object info[][];
	private Teacher t;
	/** Creates new form Insertgrade */
	public void load(String teacher, String course) {
		try {
			ArrayList<B> b = Teacher.displaycourse(teacher, course);
			Object title[] = { "序号","学生","课程", "课程老师", "分数" };
			info = new Object[b.size()][5];
			for (int i = 0; i < b.size(); i++) {
				info[i][0] = b.get(i).getId();
				info[i][1] = b.get(i).getStudent();
				info[i][2] = b.get(i).getCourse();
				info[i][3] = b.get(i).getTeacher();
				info[i][4] = b.get(i).getGrade();

			}
			this.jTable1.setModel(new DefaultTableModel(info, title));
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			
		}

	}

	public Insertgrade(String course, String teacher) {
		initComponents();
		this.setLocationRelativeTo(null);
		this.jLabel2.setText(teacher);
		this.jLabel3.setText(course);
		load(teacher,course);
		}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u6210\u7ee9\u8868");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u66f4\u65b0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u5237\u65b0");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel2.setText("jLabel2");

		jLabel3.setText("jLabel3");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554,
				Short.MAX_VALUE).addGroup(
				layout.createSequentialGroup().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addComponent(jLabel3).addGap(
														186, 186, 186)
												.addComponent(jLabel1))
								.addComponent(jLabel2)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						193, Short.MAX_VALUE).addComponent(jButton2)
						.addContainerGap()).addGroup(
				layout.createSequentialGroup().addGap(237, 237, 237)
						.addComponent(jButton1).addContainerGap(254,
								Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jButton2)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel3)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												261,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton1)
										.addContainerGap(23, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String teacher=this.jLabel2.getText();
		String course=this.jLabel3.getText();
		load(teacher,course);
	}

	@SuppressWarnings("null")
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		
		// TODO add your handling code here:
		String student = info[this.jTable1.getSelectedRow()][1]+"";
		String course = info[this.jTable1.getSelectedRow()][2]+"";
		String teacher  = info[this.jTable1.getSelectedRow()][3]+"";
		//String grade = info[this.jTable1.getSelectedRow()][4]+"";
		String grade = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 4)+"";
		try {
			Teacher.course_grade(course, teacher, student, grade);
			JOptionPane.showMessageDialog(this, "成功");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Insertgrade(null, null).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}