/*
 * user_menu.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import model.User;
import model.song;
import model.visitor;

/**
 *
 * @author  __USER__
 */
public class user_menu extends javax.swing.JFrame implements ActionListener {

	/** Creates new form user_menu 
	 * @param u */
	public user_menu(User u) {
		user = u;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 652,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 215,
				Short.MAX_VALUE));

		jScrollPane1.setViewportView(jPanel2);

		jButton1.setText("\u70b9\u6b4c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u67e5\u770b\u4eca\u5929\u6b4c\u5e93");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel1.setText("\u7528\u6237");

		jButton3.setText("\u4e0a\u4f20\u6b4c\u66f2");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		654,
																		Short.MAX_VALUE)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addGap(59, 59,
																		59)
																.addComponent(
																		jButton1)
																.addGap(113,
																		113,
																		113)
																.addComponent(
																		jButton2)
																.addGap(159,
																		159,
																		159)
																.addComponent(
																		jButton3)
																.addGap(92, 92,
																		92))))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(203, 203, 203)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										36,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(439, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(32, 32, 32)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2)
												.addComponent(jButton3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(2, 2, 2)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new song_upload().setVisible(true);

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		this.jPanel2.setVisible(false);
		chakangequ();

		this.jPanel2.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new diange().setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new user_menu(null).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
	static User user;
	JLabel[] songname = new JLabel[20];
	JLabel[] author = new JLabel[20];
	JLabel[] theme = new JLabel[20];
	JButton[] like = new JButton[20];
	JButton[] collect = new JButton[20];
	JButton[] comment_seeing = new JButton[20];
	JButton[] comment = new JButton[20];
	JPanel[] JP = new JPanel[20];
	int len = 0;

	public void chakangequ() {

		int i = 0;

		visitor v = new visitor();
		song[] s = v.geku();
		for (len = 0; len < s.length; len++) {
			try {
				songname[len] = new JLabel(s[len].getSongName());

			} catch (Exception e) {
				// TODO Auto-generated catch block
				break;
			}
		}
		songname[0] = new JLabel("歌名");
		author[0] = new JLabel("歌手");
		theme[0] = new JLabel("主题");
		like[0] = new JButton("点赞");
		collect[0] = new JButton("收藏");
		comment[0] = new JButton("评论");
		comment_seeing[0] = new JButton("查看评论");

		jPanel2.setLayout(new GridLayout(len, 5, 1, 1));
		jPanel2.add(songname[0]);
		jPanel2.add(author[0]);
		jPanel2.add(theme[0]);
		jPanel2.add(like[0]);
		jPanel2.add(collect[0]);
		jPanel2.add(comment[0]);
		jPanel2.add(comment_seeing[0]);
		//System.out.println(s.length);

		for (i = 1; i < s.length; i++) {

			try {
				songname[i] = new JLabel(s[i].getSongName());
			} catch (Exception e) {
				// TODO Auto-generated catch block
				break;
			}
			author[i] = new JLabel(s[i].getAuthor());
			theme[i] = new JLabel(s[i].getTheme());
			like[i] = new JButton("点赞");
			collect[i] = new JButton("收藏");
			comment[i] = new JButton("评论");
			comment_seeing[i] = new JButton("查看评论");

			like[i].addActionListener(this);
			comment[i].addActionListener(this);
			comment_seeing[i].addActionListener(this);
			collect[i].addActionListener(this);

			jPanel2.add(songname[i]);
			jPanel2.add(author[i]);
			jPanel2.add(theme[i]);
			jPanel2.add(like[i]);
			jPanel2.add(collect[i]);
			jPanel2.add(comment[i]);
			jPanel2.add(comment_seeing[i]);

			/*
			JP[i].add(songname[i]);
			JP[i].add(author[i]);
			JP[i].add(theme[i]);
			JP[i].add(like[i]);
			JP[i].add(collect[i]);
			jPanel2.add(JP[i]);
			 */
		}
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < len; i++) {
			if (e.getSource().equals(like[i])) {
				if (this.like[i].getText().equals("点赞")) {
					this.like[i].setText("取消点赞");

					user.dianzan(user.getUsername(), this.songname[i].getText());
				} else if (this.like[i].getText().equals("取消点赞")) {
					this.like[i].setText("点赞");

					user.quxiaodianzan(user.getUsername(),
							songname[i].getText());
				}
			}
			if (e.getSource().equals(comment[i])) {
				new comment(songname[i].getText(), user.getUsername())
						.setVisible(true);

			}
			if (e.getSource().equals(comment_seeing[i])) {
				new comment(songname[i].getText(), user.getUsername())
						.setVisible(true);
			}
			if (e.getSource().equals(collect[i])) {
				if (this.collect[i].getText().equals("收藏")) {
					this.collect[i].setText("取消收藏");
					user.shoucang(user.getUsername(), songname[i].getText());
				} else if (this.collect[i].getText().equals("取消收藏")) {
					this.collect[i].setText("收藏");
					user.quxiaoshoucang(user.getUsername(),
							songname[i].getText());
				}
			}
		}
	}
}