/*
 * visitor_menu.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import model.song;
import model.visitor;

/**
 *
 * @author  __USER__
 */
public class visitor_menu extends javax.swing.JFrame implements ActionListener {

	/** Creates new form visitor_menu */
	public visitor_menu() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new javax.swing.JPanel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u6e38\u5ba2");

		jButton1.setText("\u70b9\u6b4c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u67e5\u770b\u4eca\u5929\u6b4c\u5e93");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 664,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 215,
				Short.MAX_VALUE));

		jScrollPane1.setViewportView(jPanel2);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				666,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(170,
																				170,
																				170)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton1)
																										.addGap(113,
																												113,
																												113)
																										.addComponent(
																												jButton2))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(132,
																												132,
																												132)
																										.addComponent(
																												jLabel1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												36,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												107,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(35, 35, 35)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(38, 38, 38)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												74, Short.MAX_VALUE)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(2, 2, 2)));

		jMenu1.setText("File");

		jMenuItem1.setText("\u7528\u6237\u6ce8\u518c");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("\u7528\u6237\u767b\u9646");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("\u9000\u51fa");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("ABOUT ME");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new login().setVisible(true);
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new register().setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new diange().setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.jPanel2.removeAll();
		this.jPanel2.setVisible(false);
		chakangequ();
		this.jPanel2.setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new visitor_menu().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

	JLabel[] songname = new JLabel[20];
	JLabel[] author = new JLabel[20];
	JLabel[] theme = new JLabel[20];
	JButton[] like = new JButton[20];
	//JButton[] collect = new JButton[20];
	JButton[] comment_seeing = new JButton[20];
	JButton[] comment = new JButton[20];
	JPanel[] JP = new JPanel[20];
	int len = 0;

	public void chakangequ() {

		int i = 0;

		visitor v = new visitor();
		song[] s = v.geku();
		System.out.println(s[0].getSongName());
		for (len = 0; len < s.length; len++) {
			try {
				songname[len] = new JLabel(s[len].getSongName());

			} catch (Exception e) {
				// TODO Auto-generated catch block
				break;
			}
		}
		songname[0] = new JLabel("歌名");
		author[0] = new JLabel("歌手");
		theme[0] = new JLabel("主题");
		like[0] = new JButton("点赞");
		//collect[0] = new JButton("收藏");
		comment[0] = new JButton("评论");
		comment_seeing[0] = new JButton("查看评论");

		jPanel2.setLayout(new GridLayout(len+1, 5, 1, 1));
		jPanel2.add(songname[0]);
		jPanel2.add(author[0]);
		jPanel2.add(theme[0]);
		jPanel2.add(like[0]);
		//jPanel2.add(collect[0]);
		jPanel2.add(comment[0]);
		jPanel2.add(comment_seeing[0]);
		//System.out.println(s.length);

		for (i = 0; i < s.length; i++) {

			try {
				songname[i] = new JLabel(s[i].getSongName());
			} catch (Exception e) {
				// TODO Auto-generated catch block
				break;
			}
			author[i] = new JLabel(s[i].getAuthor());
			theme[i] = new JLabel(s[i].getTheme());
			like[i] = new JButton("点赞");
			//collect[i] = new JButton("收藏");
			comment[i] = new JButton("评论");
			comment_seeing[i] = new JButton("查看评论");

			like[i].addActionListener(this);
			comment[i].addActionListener(this);
			comment_seeing[i].addActionListener(this);
			//collect[i].addActionListener(this);
			System.out.println(songname[i].getText());
			jPanel2.add(songname[i]);
			jPanel2.add(author[i]);
			jPanel2.add(theme[i]);
			jPanel2.add(like[i]);
			//jPanel2.add(collect[i]);
			jPanel2.add(comment[i]);
			jPanel2.add(comment_seeing[i]);

			/*
			JP[i].add(songname[i]);
			JP[i].add(author[i]);
			JP[i].add(theme[i]);
			JP[i].add(like[i]);
			JP[i].add(collect[i]);
			jPanel2.add(JP[i]);
			 */
		}
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		for (int i = 0; i < len; i++) {
			if (e.getSource().equals(like[i])) {
				if (this.like[i].getText().equals("点赞")) {
					this.like[i].setText("取消点赞");
					visitor v = new visitor();
					v.dianzan("youke", this.songname[i].getText());
				} else if (this.like[i].getText().equals("取消点赞")) {
					this.like[i].setText("点赞");
					visitor v = new visitor();
					v.quxiaodianzan("youke", songname[i].getText());
				}
			}
			if (e.getSource().equals(comment[i])) {
				new comment(songname[i].getText(), "youke").setVisible(true);

			}
			if (e.getSource().equals(comment_seeing[i])) {
				new comment(songname[i].getText(), "youke").setVisible(true);
			}
		}
	}
}